// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class NodeHeartbeatMessage;
@class NodeHeartbeatMessage_Builder;
typedef enum {
  NodeHeartbeatMessage_NodeTypeRobot = 0,
  NodeHeartbeatMessage_NodeTypeTablet = 1,
  NodeHeartbeatMessage_NodeTypeSmartphone = 2,
} NodeHeartbeatMessage_NodeType;

BOOL NodeHeartbeatMessage_NodeTypeIsValidValue(NodeHeartbeatMessage_NodeType value);


@interface NodeHeartbeatMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface NodeHeartbeatMessage : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasIpaddress_:1;
  BOOL hasType_:1;
  int32_t id;
  int32_t ipaddress;
  NodeHeartbeatMessage_NodeType type;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasIpaddress;
@property (readonly) int32_t id;
@property (readonly) NodeHeartbeatMessage_NodeType type;
@property (readonly) int32_t ipaddress;

+ (NodeHeartbeatMessage*) defaultInstance;
- (NodeHeartbeatMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (NodeHeartbeatMessage_Builder*) builder;
+ (NodeHeartbeatMessage_Builder*) builder;
+ (NodeHeartbeatMessage_Builder*) builderWithPrototype:(NodeHeartbeatMessage*) prototype;

+ (NodeHeartbeatMessage*) parseFromData:(NSData*) data;
+ (NodeHeartbeatMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NodeHeartbeatMessage*) parseFromInputStream:(NSInputStream*) input;
+ (NodeHeartbeatMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (NodeHeartbeatMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (NodeHeartbeatMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface NodeHeartbeatMessage_Builder : PBGeneratedMessage_Builder {
@private
  NodeHeartbeatMessage* result;
}

- (NodeHeartbeatMessage*) defaultInstance;

- (NodeHeartbeatMessage_Builder*) clear;
- (NodeHeartbeatMessage_Builder*) clone;

- (NodeHeartbeatMessage*) build;
- (NodeHeartbeatMessage*) buildPartial;

- (NodeHeartbeatMessage_Builder*) mergeFrom:(NodeHeartbeatMessage*) other;
- (NodeHeartbeatMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (NodeHeartbeatMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (NodeHeartbeatMessage_Builder*) setId:(int32_t) value;
- (NodeHeartbeatMessage_Builder*) clearId;

- (BOOL) hasType;
- (NodeHeartbeatMessage_NodeType) type;
- (NodeHeartbeatMessage_Builder*) setType:(NodeHeartbeatMessage_NodeType) value;
- (NodeHeartbeatMessage_Builder*) clearType;

- (BOOL) hasIpaddress;
- (int32_t) ipaddress;
- (NodeHeartbeatMessage_Builder*) setIpaddress:(int32_t) value;
- (NodeHeartbeatMessage_Builder*) clearIpaddress;
@end

